name: CI

on:
  push:
    branches: [main]
    paths:
      - 'ml_eval/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'setup.py'
      - 'pytest.ini'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!examples/**'
      - '!README.md'
      - '!PROJECT_STRUCTURE.md'
      - '!LICENSE'
  pull_request:
    paths:
      - 'ml_eval/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'setup.py'
      - 'pytest.ini'
      - '.github/workflows/test.yml'
      - '!docs/**'
      - '!examples/**'
      - '!README.md'
      - '!PROJECT_STRUCTURE.md'
      - '!LICENSE'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Validate pyproject.toml
        run: |
          poetry check
      - name: Install dependencies
        run: |
          poetry install --extras dev
      - name: Validate dependencies
        run: |
          poetry show --tree

  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --extras dev
      - name: Lint, type check, and sort imports with Ruff
        run: |
          poetry run ruff check .
      - name: Check formatting with black
        run: |
          poetry run black --check .
      - name: Check formatting with ruff
        run: |
          poetry run ruff format --check .

  type-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --extras dev
      - name: Type check with Ruff
        run: |
          poetry run ruff check .

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --extras dev
      - name: Build package
        run: |
          poetry build

  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --extras dev
      - name: Run all tests
        run: |
          poetry run pytest -v --cov=ml_eval --cov-report=xml --cov-report=html --cov-report=term-missing
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./coverage.xml

#   docs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'
#       - name: Install Poetry
#         uses: snok/install-poetry@v1
#         with:
#           version: latest
#           virtualenvs-create: true
#           virtualenvs-in-project: true
#       - name: Install dependencies
#         run: |
#           poetry install --extras dev,docs
#       - name: Build docs
#         run: |
#           poetry run mkdocs build

#   publish:
#     if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'
#       - name: Install Poetry
#         uses: snok/install-poetry@v1
#         with:
#           version: latest
#           virtualenvs-create: true
#           virtualenvs-in-project: true
#       - name: Install dependencies
#         run: |
#           poetry install --extras main
#       - name: Publish to PyPI
#         env:
#           POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
#         run: |
#           poetry publish --build
