name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "export PATH=\"$HOME/.local/bin:$PATH\"" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        poetry install --only main,dev

    - name: Run all tests
      run: |
        poetry run pytest -v --cov=ml_eval --cov-report=xml --cov-report=html --cov-report=term-missing

    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
